{
 "title": "LAA Access Civil Legal Aid",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_deployment_metadata_generation, namespace)"
   },
   {
    "name": "ingress",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests{exported_namespace=\"$namespace\"},ingress)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Production DNS Site Usage",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (remote_addr) (rate(container_network_transmit_packets_total{namespace=\"laa-cla-admin-service-production\"}[1m]))",
     "legendFormat": "Usage of Access"
    },
    {
     "expr": "sum by (remote_addr) (rate(container_network_transmit_packets_total{namespace=\"laa-cla-public-production\"}[1m]))\n",
     "legendFormat": "Usage of Check"
    }
   ]
  },
  {
   "title": "DNStest DNS Site Usage",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (remote_addr) (rate(container_network_transmit_packets_total{namespace=\"laa-cla-admin-service-dnstest\"}[1m]))",
     "legendFormat": "Usage of Access"
    },
    {
     "expr": "sum by (remote_addr) (rate(container_network_transmit_packets_total{namespace=\"laa-cla-public-dnstest\"}[1m]))\n",
     "legendFormat": "Usage of Check"
    }
   ]
  },
  { "title": "Access Civil Legal Aid", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Pod Info",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{namespace='$namespace'})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum({namespace='$namespace' ,phase='Running'} + 0)",
     "legendFormat": "Running"
    },
    {
     "expr": "sum({namespace='$namespace',phase='Pending'} + 0)",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum({namespace='$namespace',phase='Failed'} + 0)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "HTTP Request Status",
   "type": "timeseries",
   "description": "The number of HTTP requests by status",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", path!~\"/socket.io/.*\", ingress=\"$ingress\", status!=\"200\"}[5m])) by (status)) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Ingress Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{exported_namespace = \"$namespace\", path !~\"/socket.io/.*\", ingress = \"$ingress\"}[5m]))",
     "legendFormat": "req / m"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod_name)(container_memory_usage_bytes{namespace='$namespace'})",
     "legendFormat": "POD: {{ pod_name}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{namespace='$namespace'})",
     "legendFormat": "Requested (soft limit)"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{namespace='$namespace'})",
     "legendFormat": "Limit (hard limit)"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum by (pod_name)(rate(container_cpu_usage_seconds_total{namespace='$namespace'}[5m]))",
     "legendFormat": "POD: {{ pod_name}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{namespace='$namespace'})",
     "legendFormat": "Requested (soft limit)"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace='$namespace'})",
     "legendFormat": "Limit (hard limit)"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sort_desc(avg(sum by (pod_name) (rate(container_network_receive_bytes_total{namespace='$namespace'}[5m]))))",
     "legendFormat": "Recv"
    },
    {
     "expr": "sort_desc(avg(sum by (pod_name) (rate(container_network_transmit_bytes_total{namespace='$namespace'}[5m]))))",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}