name: Release

run-name: Release - ${{ github.ref_name }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      CLA_ADMIN_SERVICE_ECR_REGION: ${{ vars.CLA_ADMIN_SERVICE_ECR_REGION }}
      CLA_ADMIN_SERVICE_ECR_REPOSITORY: ${{ vars.CLA_ADMIN_SERVICE_ECR_REPOSITORY }}
    secrets:
      CLA_ADMIN_SERVICE_ECR_ROLE_TO_ASSUME: ${{ secrets.CLA_ADMIN_SERVICE_ECR_ROLE_TO_ASSUME }}

  deploy-uat:
    name: UAT
    uses: ./.github/workflows/deploy.yml
    needs: build-and-push
    with:
      environment: uat
      CLA_ADMIN_SERVICE_ECR_REPOSITORY: ${{ vars.CLA_ADMIN_SERVICE_ECR_REPOSITORY }}
      DEPLOYMENT_URL: ${{ vars.UAT_DEPLOYMENT_URL }}
    secrets:
      ECR_REGISTRY_URL: ${{ secrets.ECR_REGISTRY_URL }}
      KUBE_CERT: ${{ secrets.KUBE_CERT }}
      KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}

  deploy-staging:
    name: Staging
    uses: ./.github/workflows/deploy.yml
    needs: deploy-uat
    with:
      environment: staging
      CLA_ADMIN_SERVICE_ECR_REPOSITORY: ${{ vars.CLA_ADMIN_SERVICE_ECR_REPOSITORY }}
      DEPLOYMENT_URL: ${{ vars.STAGING_DEPLOYMENT_URL }}
    secrets:
      ECR_REGISTRY_URL: ${{ secrets.ECR_REGISTRY_URL }}
      KUBE_CERT: ${{ secrets.KUBE_CERT }}
      KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}

  deploy-production:
    name: Production
    uses: ./.github/workflows/deploy.yml
    needs: deploy-staging
    with:
      environment: production
      CLA_ADMIN_SERVICE_ECR_REPOSITORY: ${{ vars.CLA_ADMIN_SERVICE_ECR_REPOSITORY }}
      DEPLOYMENT_URL: ${{ vars.PRODUCTION_DEPLOYMENT_URL }}
    secrets:
      ECR_REGISTRY_URL: ${{ secrets.ECR_REGISTRY_URL }}
      KUBE_CERT: ${{ secrets.KUBE_CERT }}
      KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
